production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5
    path: /solr/default

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/default

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
