require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CategoryTitleListMembershipsController do

  # This should return the minimal set of attributes required to create a valid
  # CategoryTitleListMembership. As you add validations to CategoryTitleListMembership, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title_list_id" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoryTitleListMembershipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all category_title_list_memberships as @category_title_list_memberships" do
      category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
      get :index, {}, valid_session
      assigns(:category_title_list_memberships).should eq([category_title_list_membership])
    end
  end

  describe "GET show" do
    it "assigns the requested category_title_list_membership as @category_title_list_membership" do
      category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
      get :show, {:id => category_title_list_membership.to_param}, valid_session
      assigns(:category_title_list_membership).should eq(category_title_list_membership)
    end
  end

  describe "GET new" do
    it "assigns a new category_title_list_membership as @category_title_list_membership" do
      get :new, {}, valid_session
      assigns(:category_title_list_membership).should be_a_new(CategoryTitleListMembership)
    end
  end

  describe "GET edit" do
    it "assigns the requested category_title_list_membership as @category_title_list_membership" do
      category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
      get :edit, {:id => category_title_list_membership.to_param}, valid_session
      assigns(:category_title_list_membership).should eq(category_title_list_membership)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CategoryTitleListMembership" do
        expect {
          post :create, {:category_title_list_membership => valid_attributes}, valid_session
        }.to change(CategoryTitleListMembership, :count).by(1)
      end

      it "assigns a newly created category_title_list_membership as @category_title_list_membership" do
        post :create, {:category_title_list_membership => valid_attributes}, valid_session
        assigns(:category_title_list_membership).should be_a(CategoryTitleListMembership)
        assigns(:category_title_list_membership).should be_persisted
      end

      it "redirects to the created category_title_list_membership" do
        post :create, {:category_title_list_membership => valid_attributes}, valid_session
        response.should redirect_to(CategoryTitleListMembership.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved category_title_list_membership as @category_title_list_membership" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryTitleListMembership.any_instance.stub(:save).and_return(false)
        post :create, {:category_title_list_membership => { "title_list_id" => "invalid value" }}, valid_session
        assigns(:category_title_list_membership).should be_a_new(CategoryTitleListMembership)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryTitleListMembership.any_instance.stub(:save).and_return(false)
        post :create, {:category_title_list_membership => { "title_list_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested category_title_list_membership" do
        category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
        # Assuming there are no other category_title_list_memberships in the database, this
        # specifies that the CategoryTitleListMembership created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CategoryTitleListMembership.any_instance.should_receive(:update_attributes).with({ "title_list_id" => "" })
        put :update, {:id => category_title_list_membership.to_param, :category_title_list_membership => { "title_list_id" => "" }}, valid_session
      end

      it "assigns the requested category_title_list_membership as @category_title_list_membership" do
        category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
        put :update, {:id => category_title_list_membership.to_param, :category_title_list_membership => valid_attributes}, valid_session
        assigns(:category_title_list_membership).should eq(category_title_list_membership)
      end

      it "redirects to the category_title_list_membership" do
        category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
        put :update, {:id => category_title_list_membership.to_param, :category_title_list_membership => valid_attributes}, valid_session
        response.should redirect_to(category_title_list_membership)
      end
    end

    describe "with invalid params" do
      it "assigns the category_title_list_membership as @category_title_list_membership" do
        category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryTitleListMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => category_title_list_membership.to_param, :category_title_list_membership => { "title_list_id" => "invalid value" }}, valid_session
        assigns(:category_title_list_membership).should eq(category_title_list_membership)
      end

      it "re-renders the 'edit' template" do
        category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryTitleListMembership.any_instance.stub(:save).and_return(false)
        put :update, {:id => category_title_list_membership.to_param, :category_title_list_membership => { "title_list_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested category_title_list_membership" do
      category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
      expect {
        delete :destroy, {:id => category_title_list_membership.to_param}, valid_session
      }.to change(CategoryTitleListMembership, :count).by(-1)
    end

    it "redirects to the category_title_list_memberships list" do
      category_title_list_membership = CategoryTitleListMembership.create! valid_attributes
      delete :destroy, {:id => category_title_list_membership.to_param}, valid_session
      response.should redirect_to(category_title_list_memberships_url)
    end
  end

end
