require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CopiesController do

  # This should return the minimal set of attributes required to create a valid
  # Copy. As you add validations to Copy, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "edition" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CopiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all copies as @copies" do
      copy = Copy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:copies).should eq([copy])
    end
  end

  describe "GET show" do
    it "assigns the requested copy as @copy" do
      copy = Copy.create! valid_attributes
      get :show, {:id => copy.to_param}, valid_session
      assigns(:copy).should eq(copy)
    end
  end

  describe "GET new" do
    it "assigns a new copy as @copy" do
      get :new, {}, valid_session
      assigns(:copy).should be_a_new(Copy)
    end
  end

  describe "GET edit" do
    it "assigns the requested copy as @copy" do
      copy = Copy.create! valid_attributes
      get :edit, {:id => copy.to_param}, valid_session
      assigns(:copy).should eq(copy)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Copy" do
        expect {
          post :create, {:copy => valid_attributes}, valid_session
        }.to change(Copy, :count).by(1)
      end

      it "assigns a newly created copy as @copy" do
        post :create, {:copy => valid_attributes}, valid_session
        assigns(:copy).should be_a(Copy)
        assigns(:copy).should be_persisted
      end

      it "redirects to the created copy" do
        post :create, {:copy => valid_attributes}, valid_session
        response.should redirect_to(Copy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved copy as @copy" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copy.any_instance.stub(:save).and_return(false)
        post :create, {:copy => { "edition" => "invalid value" }}, valid_session
        assigns(:copy).should be_a_new(Copy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Copy.any_instance.stub(:save).and_return(false)
        post :create, {:copy => { "edition" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested copy" do
        copy = Copy.create! valid_attributes
        # Assuming there are no other copies in the database, this
        # specifies that the Copy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Copy.any_instance.should_receive(:update_attributes).with({ "edition" => "" })
        put :update, {:id => copy.to_param, :copy => { "edition" => "" }}, valid_session
      end

      it "assigns the requested copy as @copy" do
        copy = Copy.create! valid_attributes
        put :update, {:id => copy.to_param, :copy => valid_attributes}, valid_session
        assigns(:copy).should eq(copy)
      end

      it "redirects to the copy" do
        copy = Copy.create! valid_attributes
        put :update, {:id => copy.to_param, :copy => valid_attributes}, valid_session
        response.should redirect_to(copy)
      end
    end

    describe "with invalid params" do
      it "assigns the copy as @copy" do
        copy = Copy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copy.any_instance.stub(:save).and_return(false)
        put :update, {:id => copy.to_param, :copy => { "edition" => "invalid value" }}, valid_session
        assigns(:copy).should eq(copy)
      end

      it "re-renders the 'edit' template" do
        copy = Copy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Copy.any_instance.stub(:save).and_return(false)
        put :update, {:id => copy.to_param, :copy => { "edition" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested copy" do
      copy = Copy.create! valid_attributes
      expect {
        delete :destroy, {:id => copy.to_param}, valid_session
      }.to change(Copy, :count).by(-1)
    end

    it "redirects to the copies list" do
      copy = Copy.create! valid_attributes
      delete :destroy, {:id => copy.to_param}, valid_session
      response.should redirect_to(copies_url)
    end
  end

end
