require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EditionsController do

  # This should return the minimal set of attributes required to create a valid
  # Edition. As you add validations to Edition, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "isbn13" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EditionsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all editions as @editions" do
      edition = Edition.create! valid_attributes
      get :index, {}, valid_session
      assigns(:editions).should eq([edition])
    end
  end

  describe "GET show" do
    it "assigns the requested edition as @edition" do
      edition = Edition.create! valid_attributes
      get :show, {:id => edition.to_param}, valid_session
      assigns(:edition).should eq(edition)
    end
  end

  describe "GET new" do
    it "assigns a new edition as @edition" do
      get :new, {}, valid_session
      assigns(:edition).should be_a_new(Edition)
    end
  end

  describe "GET edit" do
    it "assigns the requested edition as @edition" do
      edition = Edition.create! valid_attributes
      get :edit, {:id => edition.to_param}, valid_session
      assigns(:edition).should eq(edition)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Edition" do
        expect {
          post :create, {:edition => valid_attributes}, valid_session
        }.to change(Edition, :count).by(1)
      end

      it "assigns a newly created edition as @edition" do
        post :create, {:edition => valid_attributes}, valid_session
        assigns(:edition).should be_a(Edition)
        assigns(:edition).should be_persisted
      end

      it "redirects to the created edition" do
        post :create, {:edition => valid_attributes}, valid_session
        response.should redirect_to(Edition.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved edition as @edition" do
        # Trigger the behavior that occurs when invalid params are submitted
        Edition.any_instance.stub(:save).and_return(false)
        post :create, {:edition => { "isbn13" => "invalid value" }}, valid_session
        assigns(:edition).should be_a_new(Edition)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Edition.any_instance.stub(:save).and_return(false)
        post :create, {:edition => { "isbn13" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested edition" do
        edition = Edition.create! valid_attributes
        # Assuming there are no other editions in the database, this
        # specifies that the Edition created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Edition.any_instance.should_receive(:update_attributes).with({ "isbn13" => "MyString" })
        put :update, {:id => edition.to_param, :edition => { "isbn13" => "MyString" }}, valid_session
      end

      it "assigns the requested edition as @edition" do
        edition = Edition.create! valid_attributes
        put :update, {:id => edition.to_param, :edition => valid_attributes}, valid_session
        assigns(:edition).should eq(edition)
      end

      it "redirects to the edition" do
        edition = Edition.create! valid_attributes
        put :update, {:id => edition.to_param, :edition => valid_attributes}, valid_session
        response.should redirect_to(edition)
      end
    end

    describe "with invalid params" do
      it "assigns the edition as @edition" do
        edition = Edition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Edition.any_instance.stub(:save).and_return(false)
        put :update, {:id => edition.to_param, :edition => { "isbn13" => "invalid value" }}, valid_session
        assigns(:edition).should eq(edition)
      end

      it "re-renders the 'edit' template" do
        edition = Edition.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Edition.any_instance.stub(:save).and_return(false)
        put :update, {:id => edition.to_param, :edition => { "isbn13" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested edition" do
      edition = Edition.create! valid_attributes
      expect {
        delete :destroy, {:id => edition.to_param}, valid_session
      }.to change(Edition, :count).by(-1)
    end

    it "redirects to the editions list" do
      edition = Edition.create! valid_attributes
      delete :destroy, {:id => edition.to_param}, valid_session
      response.should redirect_to(editions_url)
    end
  end

end
