require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe InventoryCopyConfirmationsController do

  # This should return the minimal set of attributes required to create a valid
  # InventoryCopyConfirmation. As you add validations to InventoryCopyConfirmation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "inventory" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # InventoryCopyConfirmationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all inventory_copy_confirmations as @inventory_copy_confirmations" do
      inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:inventory_copy_confirmations).should eq([inventory_copy_confirmation])
    end
  end

  describe "GET show" do
    it "assigns the requested inventory_copy_confirmation as @inventory_copy_confirmation" do
      inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
      get :show, {:id => inventory_copy_confirmation.to_param}, valid_session
      assigns(:inventory_copy_confirmation).should eq(inventory_copy_confirmation)
    end
  end

  describe "GET new" do
    it "assigns a new inventory_copy_confirmation as @inventory_copy_confirmation" do
      get :new, {}, valid_session
      assigns(:inventory_copy_confirmation).should be_a_new(InventoryCopyConfirmation)
    end
  end

  describe "GET edit" do
    it "assigns the requested inventory_copy_confirmation as @inventory_copy_confirmation" do
      inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
      get :edit, {:id => inventory_copy_confirmation.to_param}, valid_session
      assigns(:inventory_copy_confirmation).should eq(inventory_copy_confirmation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new InventoryCopyConfirmation" do
        expect {
          post :create, {:inventory_copy_confirmation => valid_attributes}, valid_session
        }.to change(InventoryCopyConfirmation, :count).by(1)
      end

      it "assigns a newly created inventory_copy_confirmation as @inventory_copy_confirmation" do
        post :create, {:inventory_copy_confirmation => valid_attributes}, valid_session
        assigns(:inventory_copy_confirmation).should be_a(InventoryCopyConfirmation)
        assigns(:inventory_copy_confirmation).should be_persisted
      end

      it "redirects to the created inventory_copy_confirmation" do
        post :create, {:inventory_copy_confirmation => valid_attributes}, valid_session
        response.should redirect_to(InventoryCopyConfirmation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved inventory_copy_confirmation as @inventory_copy_confirmation" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryCopyConfirmation.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_copy_confirmation => { "inventory" => "invalid value" }}, valid_session
        assigns(:inventory_copy_confirmation).should be_a_new(InventoryCopyConfirmation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryCopyConfirmation.any_instance.stub(:save).and_return(false)
        post :create, {:inventory_copy_confirmation => { "inventory" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested inventory_copy_confirmation" do
        inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
        # Assuming there are no other inventory_copy_confirmations in the database, this
        # specifies that the InventoryCopyConfirmation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        InventoryCopyConfirmation.any_instance.should_receive(:update_attributes).with({ "inventory" => "" })
        put :update, {:id => inventory_copy_confirmation.to_param, :inventory_copy_confirmation => { "inventory" => "" }}, valid_session
      end

      it "assigns the requested inventory_copy_confirmation as @inventory_copy_confirmation" do
        inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
        put :update, {:id => inventory_copy_confirmation.to_param, :inventory_copy_confirmation => valid_attributes}, valid_session
        assigns(:inventory_copy_confirmation).should eq(inventory_copy_confirmation)
      end

      it "redirects to the inventory_copy_confirmation" do
        inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
        put :update, {:id => inventory_copy_confirmation.to_param, :inventory_copy_confirmation => valid_attributes}, valid_session
        response.should redirect_to(inventory_copy_confirmation)
      end
    end

    describe "with invalid params" do
      it "assigns the inventory_copy_confirmation as @inventory_copy_confirmation" do
        inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryCopyConfirmation.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_copy_confirmation.to_param, :inventory_copy_confirmation => { "inventory" => "invalid value" }}, valid_session
        assigns(:inventory_copy_confirmation).should eq(inventory_copy_confirmation)
      end

      it "re-renders the 'edit' template" do
        inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        InventoryCopyConfirmation.any_instance.stub(:save).and_return(false)
        put :update, {:id => inventory_copy_confirmation.to_param, :inventory_copy_confirmation => { "inventory" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested inventory_copy_confirmation" do
      inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
      expect {
        delete :destroy, {:id => inventory_copy_confirmation.to_param}, valid_session
      }.to change(InventoryCopyConfirmation, :count).by(-1)
    end

    it "redirects to the inventory_copy_confirmations list" do
      inventory_copy_confirmation = InventoryCopyConfirmation.create! valid_attributes
      delete :destroy, {:id => inventory_copy_confirmation.to_param}, valid_session
      response.should redirect_to(inventory_copy_confirmations_url)
    end
  end

end
