require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PostTitleListLinksController do

  # This should return the minimal set of attributes required to create a valid
  # PostTitleListLink. As you add validations to PostTitleListLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "post" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PostTitleListLinksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all post_title_list_links as @post_title_list_links" do
      post_title_list_link = PostTitleListLink.create! valid_attributes
      get :index, {}, valid_session
      assigns(:post_title_list_links).should eq([post_title_list_link])
    end
  end

  describe "GET show" do
    it "assigns the requested post_title_list_link as @post_title_list_link" do
      post_title_list_link = PostTitleListLink.create! valid_attributes
      get :show, {:id => post_title_list_link.to_param}, valid_session
      assigns(:post_title_list_link).should eq(post_title_list_link)
    end
  end

  describe "GET new" do
    it "assigns a new post_title_list_link as @post_title_list_link" do
      get :new, {}, valid_session
      assigns(:post_title_list_link).should be_a_new(PostTitleListLink)
    end
  end

  describe "GET edit" do
    it "assigns the requested post_title_list_link as @post_title_list_link" do
      post_title_list_link = PostTitleListLink.create! valid_attributes
      get :edit, {:id => post_title_list_link.to_param}, valid_session
      assigns(:post_title_list_link).should eq(post_title_list_link)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PostTitleListLink" do
        expect {
          post :create, {:post_title_list_link => valid_attributes}, valid_session
        }.to change(PostTitleListLink, :count).by(1)
      end

      it "assigns a newly created post_title_list_link as @post_title_list_link" do
        post :create, {:post_title_list_link => valid_attributes}, valid_session
        assigns(:post_title_list_link).should be_a(PostTitleListLink)
        assigns(:post_title_list_link).should be_persisted
      end

      it "redirects to the created post_title_list_link" do
        post :create, {:post_title_list_link => valid_attributes}, valid_session
        response.should redirect_to(PostTitleListLink.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved post_title_list_link as @post_title_list_link" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostTitleListLink.any_instance.stub(:save).and_return(false)
        post :create, {:post_title_list_link => { "post" => "invalid value" }}, valid_session
        assigns(:post_title_list_link).should be_a_new(PostTitleListLink)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PostTitleListLink.any_instance.stub(:save).and_return(false)
        post :create, {:post_title_list_link => { "post" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested post_title_list_link" do
        post_title_list_link = PostTitleListLink.create! valid_attributes
        # Assuming there are no other post_title_list_links in the database, this
        # specifies that the PostTitleListLink created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PostTitleListLink.any_instance.should_receive(:update_attributes).with({ "post" => "" })
        put :update, {:id => post_title_list_link.to_param, :post_title_list_link => { "post" => "" }}, valid_session
      end

      it "assigns the requested post_title_list_link as @post_title_list_link" do
        post_title_list_link = PostTitleListLink.create! valid_attributes
        put :update, {:id => post_title_list_link.to_param, :post_title_list_link => valid_attributes}, valid_session
        assigns(:post_title_list_link).should eq(post_title_list_link)
      end

      it "redirects to the post_title_list_link" do
        post_title_list_link = PostTitleListLink.create! valid_attributes
        put :update, {:id => post_title_list_link.to_param, :post_title_list_link => valid_attributes}, valid_session
        response.should redirect_to(post_title_list_link)
      end
    end

    describe "with invalid params" do
      it "assigns the post_title_list_link as @post_title_list_link" do
        post_title_list_link = PostTitleListLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostTitleListLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_title_list_link.to_param, :post_title_list_link => { "post" => "invalid value" }}, valid_session
        assigns(:post_title_list_link).should eq(post_title_list_link)
      end

      it "re-renders the 'edit' template" do
        post_title_list_link = PostTitleListLink.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PostTitleListLink.any_instance.stub(:save).and_return(false)
        put :update, {:id => post_title_list_link.to_param, :post_title_list_link => { "post" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested post_title_list_link" do
      post_title_list_link = PostTitleListLink.create! valid_attributes
      expect {
        delete :destroy, {:id => post_title_list_link.to_param}, valid_session
      }.to change(PostTitleListLink, :count).by(-1)
    end

    it "redirects to the post_title_list_links list" do
      post_title_list_link = PostTitleListLink.create! valid_attributes
      delete :destroy, {:id => post_title_list_link.to_param}, valid_session
      response.should redirect_to(post_title_list_links_url)
    end
  end

end
